### ISSUE TITLE
Train stops with empty wait condition

### ISSUE THREAD

**Issue by Calibretto22** [DaveMcW/blueprint-train#1]
If there is a train schedule with a destination that has no wait condition, the empty destination is not properly rebuilt in the schedule when blueprinted.

**Comment by Calibretto22** [comment]
![image](https://user-images.githubusercontent.com/29695655/45253598-4cba8e80-b36a-11e8-9ca7-74fd7d46a102.png)

**Comment by DaveMcW** [comment]
Thanks, fixed in version 0.16.17.
