### ISSUE TITLE
ghosted entites inhibit blueprint of trains

### ISSUE THREAD

**Issue by Calibretto22** [DaveMcW/blueprint-train#2]
when there is a ghosted entity in the same blueprint as a train, the train is not added to the blueprint. 

![image](https://user-images.githubusercontent.com/29695655/45253689-9bb4f380-b36b-11e8-8ba8-e6a1a8f46d49.png)

(i did not test for interference with other mods)

**Comment by DaveMcW** [comment]
Thanks, fixed in version 0.16.17
